"""Pydantic task packet model for dry-run maintainer delegation."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

MAINTAINER_PACKET_SCHEMA_VERSION = "maintainer-task-packet/v0"


class TaskPacket(BaseModel):
    """Semantic task packet for a delegated coding worker.

    The packet is intentionally a dry-run planning artifact. It describes what a future worker may
    read, which paths it intends to write, what it must not touch, and how Hermes will verify the
    outcome. It does not execute OpenHands, OpenShell, GitHub, or any live provider.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: Literal["maintainer-task-packet/v0"] = MAINTAINER_PACKET_SCHEMA_VERSION
    objective: str = Field(min_length=1)
    mode: Literal["dry_run"] = "dry_run"
    allowed_paths: tuple[str, ...] = Field(min_length=1)
    forbidden_paths: tuple[str, ...] = Field(default_factory=tuple)
    required_reads: tuple[str, ...] = Field(min_length=1)
    required_commands: tuple[str, ...] = Field(min_length=1)
    stop_conditions: tuple[str, ...] = Field(min_length=1)

    @field_validator(
        "objective",
        "allowed_paths",
        "forbidden_paths",
        "required_reads",
        "required_commands",
        "stop_conditions",
        mode="before",
    )
    @classmethod
    def _reject_blank_values(cls, value: object) -> object:
        if isinstance(value, str) and not value.strip():
            raise ValueError("value must not be blank")
        if isinstance(value, list | tuple):
            for item in value:
                if not isinstance(item, str) or not item.strip():
                    raise ValueError("list values must be non-blank strings")
        return value

    @field_validator("allowed_paths", "forbidden_paths", "required_reads")
    @classmethod
    def _paths_are_relative(cls, paths: tuple[str, ...]) -> tuple[str, ...]:
        for path in paths:
            if path.startswith("/"):
                raise ValueError("paths must be repository-relative")
            if ".." in path.split("/"):
                raise ValueError("paths must not traverse upward")
        return paths

    @model_validator(mode="after")
    def _required_reads_cover_packet(self) -> TaskPacket:
        missing = [path for path in self.required_reads if path in self.forbidden_paths]
        if missing:
            raise ValueError(f"required reads must not include forbidden paths: {', '.join(missing)}")
        return self


def render_task_markdown(packet: TaskPacket) -> str:
    """Render a deterministic ``task.md`` body for a delegated worker."""
    lines: list[str] = [
        "# Build Arena maintainer delegation task",
        "",
        "Generated by Hermes as a dry-run task packet. This is not an execution receipt.",
        "",
        "## Objective",
        packet.objective,
        "",
        "## Mode",
        packet.mode,
        "",
        "## Allowed write path intent",
        *_bullet_lines(packet.allowed_paths),
        "",
        "## Forbidden path intent",
        *_bullet_lines(packet.forbidden_paths),
        "",
        "## Required reads before writing",
        *_bullet_lines(packet.required_reads),
        "",
        "## Required verification commands",
        "```sh",
        *packet.required_commands,
        "```",
        "",
        "## Stop conditions",
        *_bullet_lines(packet.stop_conditions),
        "",
        "## Delegation boundaries",
        "- Do not apply, promote, auto-merge, push, or mutate a target repository.",
        "- Do not execute OpenHands in this slice.",
        "- Do not create or enter a live OpenShell sandbox in this slice.",
        "- Hermes owns semantic authorization and final verification.",
    ]
    return "\n".join(lines) + "\n"


def _bullet_lines(values: tuple[str, ...]) -> list[str]:
    if not values:
        return ["- (none)"]
    return [f"- `{value}`" for value in values]
