version = 1
scorer_sha = "5ace715ed8e522f9ba5dc977086fcce47b3efe7999376ebe36d861975095ee0d"
locked_files = [
    "scorer/__init__.py",
    "scorer/engine.py",
    "scorer/exceptions.py",
    "scorer/goal_config.py",
    "scorer/lock.py",
]
